<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace GPBMetadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ƒ

user.proto"Q
	UserModel

Id (
Name (	
Sex (
Status (
Ctime ("
listReq
size (	"B
ListRes
code (
message (	
data (2
.UserModel"B
addReq
Name (	
Sex (
Status (
Ctime ("A
addRes
code (
message (	
data (2
.UserModel"
	deleteReq

Id ("*
	deleteRes
code (
message (	2b
	UserProto
List.listReq.ListRes
Add.addReq.addRes 
Delete
.deleteReq
.deleteResBZ./userProtobproto3'
        , true);

        static::$is_initialized = true;
    }
}

