<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace GPBMetadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
—

user.proto	userProto"Q
	UserModel

Id (
Name (	
Sex (
Status (
Ctime (",
listRequest
keyword (	
size (	"Q
listResponse
code (
message (	"
data (2.userProto.UserModel"F

addRequest
Name (	
Sex (
Status (
Ctime ("P
addResponse
code (
message (	"
data (2.userProto.UserModel"
deleteRequest

Id ("/
deleteResponse
code (
message (	2¹
	UserProto7
List.userProto.listRequest.userProto.listResponse4
Add.userProto.addRequest.userProto.addResponse=
Delete.userProto.deleteRequest.userProto.deleteResponsebproto3'
        , true);

        static::$is_initialized = true;
    }
}

